package com.passdrop.passwordgen.domain

import java.security.SecureRandom

object PassphraseGenerator {
    
    private val WORD_LIST = listOf(
        "about", "above", "across", "action", "active", "actor", "actual", "adopt", "adult", "after",
        "again", "against", "agency", "agent", "agree", "ahead", "allow", "almost", "alone", "along",
        "already", "also", "always", "among", "amount", "ancient", "animal", "another", "answer", "anyone",
        "anything", "appear", "apply", "approach", "area", "argue", "arise", "around", "arrive", "article",
        "artist", "assume", "attack", "attempt", "attend", "author", "avoid", "aware", "away", "baby",
        "back", "balance", "ball", "bank", "base", "basic", "battle", "beach", "bear", "beat",
        "beauty", "become", "before", "begin", "behavior", "behind", "belief", "believe", "below", "benefit",
        "best", "better", "between", "beyond", "billion", "birth", "black", "block", "blood", "blow",
        "blue", "board", "boat", "body", "book", "born", "both", "bottom", "brain", "branch",
        "brave", "break", "bridge", "brief", "bright", "bring", "broad", "broken", "brother", "brown",
        "budget", "build", "building", "business", "call", "camera", "campaign", "campus", "cancer", "candidate",
        "capital", "captain", "capture", "carbon", "card", "care", "career", "carry", "case", "cash",
        "cast", "catch", "cause", "ceiling", "celebrate", "cell", "center", "central", "century", "certain",
        "chair", "chairman", "challenge", "chamber", "champion", "chance", "change", "chapter", "character", "charge",
        "charity", "chart", "chase", "cheap", "check", "cheese", "chemical", "chest", "chief", "child",
        "choice", "choose", "church", "citizen", "city", "civil", "claim", "class", "classic", "clean",
        "clear", "client", "climate", "climb", "clock", "close", "clothes", "cloud", "club", "coach",
        "coal", "coast", "coat", "code", "coffee", "cold", "collect", "college", "color", "column",
        "combine", "come", "comfort", "command", "comment", "commerce", "commit", "common", "community", "company",
        "compare", "compete", "complete", "complex", "computer", "concept", "concern", "concert", "conclude", "condition",
        "conduct", "conference", "confirm", "conflict", "congress", "connect", "consider", "consist", "constant", "construct",
        "consult", "consume", "contact", "contain", "content", "contest", "context", "continue", "contract", "contrast",
        "contribute", "control", "convention", "convert", "cook", "cool", "copper", "copy", "core", "corner",
        "corporate", "correct", "cost", "cottage", "cotton", "council", "count", "country", "county", "couple",
        "courage", "course", "court", "cousin", "cover", "crack", "craft", "crash", "crazy", "cream",
        "create", "credit", "crew", "crime", "crisis", "critical", "crop", "cross", "crowd", "crown",
        "crucial", "culture", "current", "custom", "customer", "cycle", "daily", "damage", "dance", "danger",
        "dark", "data", "date", "daughter", "dawn", "dead", "deal", "dealer", "dear", "death",
        "debate", "debt", "decade", "decide", "decision", "declare", "decline", "deep", "defeat", "defend",
        "defense", "define", "degree", "delay", "deliver", "demand", "democracy", "demonstrate", "deny", "department",
        "depend", "deputy", "derive", "describe", "desert", "design", "desire", "desk", "despite", "destroy",
        "detail", "detect", "determine", "develop", "device", "devote", "dialogue", "diamond", "diary", "differ",
        "digital", "dinner", "direct", "director", "dirt", "discover", "discuss", "disease", "display", "dispute",
        "distance", "distinct", "district", "diverse", "divide", "division", "doctor", "document", "dollar", "domain",
        "domestic", "dominant", "dominate", "door", "double", "doubt", "down", "downtown", "dozen", "draft",
        "drag", "drama", "dramatic", "draw", "dream", "dress", "drink", "drive", "driver", "drop",
        "drug", "during", "dust", "duty", "each", "eager", "early", "earn", "earth", "ease",
        "east", "eastern", "easy", "economic", "economy", "edge", "edit", "editor", "educate", "education",
        "effect", "effective", "effort", "eight", "either", "elect", "election", "electric", "element", "eliminate",
        "elite", "else", "elsewhere", "embrace", "emerge", "emission", "emotion", "emphasis", "employ", "employee",
        "employer", "empty", "enable", "encounter", "encourage", "enemy", "energy", "enforce", "engage", "engine",
        "engineer", "enhance", "enjoy", "enough", "ensure", "enter", "entire", "entry", "environment", "equal",
        "error", "escape", "especially", "essay", "essential", "establish", "estate", "estimate", "ethical", "ethnic",
        "evaluate", "even", "evening", "event", "eventually", "ever", "every", "everybody", "everyone", "everything",
        "everywhere", "evidence", "evident", "evil", "evolution", "evolve", "exact", "examine", "example", "exceed",
        "excellent", "except", "exchange", "exciting", "exclude", "executive", "exercise", "exhibit", "exist", "exit",
        "expand", "expect", "expense", "expensive", "experience", "experiment", "expert", "explain", "explode", "explore",
        "export", "expose", "express", "extend", "extension", "extensive", "extent", "external", "extra", "extraordinary",
        "extreme", "fabric", "face", "facility", "fact", "factor", "factory", "faculty", "fade", "fail",
        "failure", "fair", "faith", "fall", "false", "familiar", "family", "famous", "fantasy", "farm",
        "farmer", "fashion", "fast", "father", "fault", "favor", "favorite", "fear", "feature", "federal",
        "feel", "feeling", "fellow", "female", "fence", "festival", "fewer", "fiber", "fiction", "field",
        "fifteen", "fifth", "fifty", "fight", "fighter", "figure", "file", "fill", "film", "final",
        "finance", "financial", "find", "finding", "fine", "finger", "finish", "fire", "firm", "first",
        "fish", "fishing", "fitness", "five", "fixed", "flag", "flame", "flat", "flavor", "flee",
        "flesh", "flight", "float", "floor", "flow", "flower", "fluid", "focus", "folk", "follow",
        "food", "football", "force", "forecast", "foreign", "forest", "forever", "forget", "form", "formal",
        "format", "former", "formula", "forth", "fortune", "forward", "found", "foundation", "founder", "four",
        "fourth", "frame", "framework", "free", "freedom", "freeze", "French", "frequency", "frequent", "fresh",
        "friend", "friendly", "from", "front", "fruit", "frustrate", "fuel", "full", "fully", "function",
        "fund", "fundamental", "funding", "funny", "furniture", "furthermore", "future", "gain", "galaxy", "gallery",
        "game", "gang", "garden", "garlic", "gate", "gather", "gave", "gear", "gender", "gene",
        "general", "generate", "generation", "genetic", "genius", "genre", "gentle", "gentleman", "genuine", "gesture",
        "ghost", "giant", "gift", "girl", "give", "given", "glad", "glance", "glass", "global",
        "glory", "goal", "gold", "golden", "golf", "good", "government", "governor", "grab", "grade",
        "gradually", "graduate", "grain", "grand", "grant", "grass", "grave", "gray", "great", "green",
        "grocery", "ground", "group", "grow", "growth", "guarantee", "guard", "guess", "guest", "guide",
        "guideline", "guilty", "guitar", "half", "hall", "hand", "handful", "handle", "hang", "happen",
        "happy", "hard", "hardly", "harm", "harsh", "hate", "have", "head", "headline", "headquarters",
        "health", "healthy", "hear", "hearing", "heart", "heat", "heaven", "heavily", "heavy", "heel",
        "height", "help", "helpful", "heritage", "hero", "herself", "hide", "high", "highlight", "highly",
        "highway", "hill", "himself", "hire", "historian", "historic", "historical", "history", "hold", "hole",
        "holiday", "holy", "home", "homeless", "honest", "honey", "honor", "hope", "horizon", "horror",
        "horse", "hospital", "host", "hotel", "hour", "house", "household", "housing", "however", "huge",
        "human", "humor", "hundred", "hungry", "hunter", "hunting", "hurt", "husband", "hypothesis", "idea",
        "ideal", "identify", "identity", "ignore", "illegal", "illustrate", "image", "imagine", "immediate", "immigrant",
        "immigration", "impact", "implement", "implication", "imply", "import", "importance", "important", "impose", "impossible",
        "impress", "improve", "incentive", "incident", "include", "income", "incorporate", "increase", "increasingly", "incredible",
        "indeed", "independent", "index", "indicate", "individual", "industrial", "industry", "infant", "infect", "inflation",
        "influence", "inform", "information", "ingredient", "initial", "initiative", "injury", "inner", "innocent", "innovation",
        "input", "inquiry", "inside", "insight", "insist", "inspire", "install", "instance", "instead", "institution",
        "instruction", "instructor", "instrument", "insurance", "intellectual", "intelligence", "intend", "intense", "intention", "interact",
        "interest", "interior", "internal", "international", "interpret", "interval", "intervention", "interview", "into", "introduce",
        "invasion", "invest", "investigate", "investment", "investor", "invite", "involve", "iron", "island", "isolate",
        "issue", "item", "itself", "jacket", "jail", "Japanese", "joke", "journal", "journalist", "journey",
        "judge", "judgment", "juice", "jump", "junior", "jury", "just", "justice", "justify", "keep",
        "key", "kick", "kill", "killer", "kind", "king", "kitchen", "knee", "knife", "knock",
        "know", "knowledge", "label", "labor", "laboratory", "lack", "lady", "lake", "land", "landscape",
        "language", "large", "largely", "last", "late", "later", "Latin", "latter", "laugh", "launch",
        "lawn", "lawsuit", "lawyer", "layer", "lead", "leader", "leadership", "leading", "leaf", "league",
        "lean", "learn", "least", "leather", "leave", "left", "legacy", "legal", "legend", "legislation",
        "legislative", "legitimate", "lemon", "length", "less", "lesson", "letter", "level", "liberal", "library",
        "license", "life", "lifestyle", "lifetime", "lift", "light", "like", "likely", "limit", "line",
        "link", "lion", "list", "listen", "literally", "literary", "literature", "little", "live", "living",
        "load", "loan", "local", "locate", "location", "lock", "long", "look", "loose", "lose",
        "loss", "lost", "love", "lovely", "lover", "lower", "luck", "lucky", "lunch", "lung",
        "machine", "magazine", "magic", "mail", "main", "mainly", "maintain", "maintenance", "major", "majority",
        "make", "maker", "makeup", "male", "mall", "manage", "management", "manager", "manner", "manufacturer",
        "manufacturing", "many", "margin", "mark", "market", "marketing", "marriage", "married", "marry", "mask",
        "mass", "massive", "master", "match", "material", "math", "matter", "maximum", "maybe", "mayor",
        "meal", "mean", "meaning", "meanwhile", "measure", "meat", "mechanism", "media", "medical", "medication",
        "medicine", "medium", "meet", "meeting", "member", "membership", "memory", "mental", "mention", "menu",
        "mere", "merely", "merit", "mess", "message", "metal", "meter", "method", "middle", "might",
        "military", "milk", "million", "mind", "mine", "minister", "minor", "minority", "minute", "miracle",
        "mirror", "miss", "missile", "mission", "mistake", "mixed", "mixture", "mode", "model", "moderate",
        "modern", "modest", "modify", "moment", "money", "monitor", "month", "mood", "moon", "moral",
        "more", "moreover", "morning", "mortgage", "most", "mostly", "mother", "motion", "motivation", "motor",
        "mount", "mountain", "mouse", "mouth", "move", "movement", "movie", "much", "multiple", "murder",
        "muscle", "museum", "music", "musical", "musician", "must", "mutual", "myself", "mystery", "myth",
        "naked", "name", "narrative", "narrow", "nation", "national", "native", "natural", "naturally", "nature",
        "naval", "near", "nearby", "nearly", "necessary", "neck", "need", "negative", "negotiate", "neighbor",
        "neighborhood", "neither", "nerve", "nervous", "network", "never", "nevertheless", "news", "newspaper", "next",
        "nice", "night", "nine", "nobody", "noise", "nominate", "none", "nonetheless", "norm", "normal",
        "normally", "north", "northern", "nose", "note", "nothing", "notice", "notion", "novel", "now",
        "nowhere", "nuclear", "number", "numerous", "nurse", "object", "objective", "obligation", "observe", "observer",
        "obtain", "obvious", "obviously", "occasion", "occasional", "occupy", "occur", "ocean", "odds", "offense",
        "offer", "office", "officer", "official", "often", "okay", "once", "ongoing", "onion", "online",
        "only", "onto", "open", "opening", "operate", "operating", "operation", "operator", "opinion", "opponent",
        "opportunity", "oppose", "opposite", "opposition", "option", "orange", "order", "ordinary", "organic", "organization",
        "organize", "orientation", "origin", "original", "other", "others", "otherwise", "ought", "outcome", "outside",
        "oven", "over", "overall", "overcome", "overlook", "owe", "owner", "pace", "pack", "package",
        "page", "pain", "painful", "paint", "painter", "painting", "pair", "palace", "pale", "palm",
        "panel", "pant", "paper", "parent", "park", "parking", "part", "participant", "participate", "particular",
        "particularly", "partly", "partner", "partnership", "party", "pass", "passage", "passenger", "passion", "past",
        "patch", "path", "patient", "pattern", "pause", "payment", "peace", "peak", "peer", "penalty",
        "people", "pepper", "perceive", "percent", "percentage", "perception", "perfect", "perform", "performance", "perhaps",
        "period", "permanent", "permission", "permit", "person", "personal", "personality", "personally", "personnel", "perspective",
        "persuade", "phase", "phenomenon", "philosophy", "phone", "photo", "photograph", "photographer", "phrase", "physical",
        "physician", "piano", "pick", "picture", "piece", "pile", "pilot", "pine", "pink", "pipe",
        "pitch", "place", "plan", "plane", "planet", "planning", "plant", "plastic", "plate", "platform",
        "play", "player", "please", "pleasure", "plenty", "plot", "plus", "pocket", "poem", "poet",
        "poetry", "point", "pole", "police", "policy", "political", "politician", "politics", "poll", "pollution",
        "pool", "poor", "popular", "population", "porch", "port", "portion", "portrait", "portray", "pose",
        "position", "positive", "possess", "possibility", "possible", "possibly", "post", "potato", "potential", "pound",
        "pour", "poverty", "powder", "power", "powerful", "practical", "practice", "pray", "prayer", "precise",
        "predict", "prefer", "preference", "pregnancy", "pregnant", "preparation", "prepare", "prescription", "presence", "present",
        "presentation", "preserve", "president", "presidential", "press", "pressure", "pretend", "pretty", "prevent", "previous",
        "previously", "price", "pride", "priest", "primarily", "primary", "prime", "principal", "principle", "print",
        "prior", "priority", "prison", "prisoner", "privacy", "private", "probably", "problem", "procedure", "proceed",
        "process", "produce", "producer", "product", "production", "profession", "professional", "professor", "profile", "profit",
        "program", "progress", "project", "prominent", "promise", "promote", "prompt", "proof", "proper", "properly",
        "property", "proportion", "proposal", "propose", "proposed", "prosecutor", "prospect", "protect", "protection", "protein",
        "protest", "proud", "prove", "provide", "provider", "province", "provision", "psychological", "psychologist", "psychology",
        "public", "publication", "publicly", "publish", "publisher", "pull", "punishment", "purchase", "pure", "purpose",
        "pursue", "push", "qualify", "quality", "quarter", "quarterback", "queen", "question", "quick", "quickly",
        "quiet", "quietly", "quit", "quite", "quote", "race", "racial", "radical", "radio", "rail",
        "rain", "raise", "range", "rank", "rapid", "rapidly", "rare", "rarely", "rate", "rather",
        "rating", "ratio", "reach", "react", "reaction", "read", "reader", "reading", "ready", "real",
        "reality", "realize", "really", "reason", "reasonable", "recall", "receive", "recent", "recently", "recipe",
        "recognize", "recommend", "recommendation", "record", "recording", "recover", "recovery", "recruit", "reduce", "reduction",
        "refer", "reference", "reflect", "reflection", "reform", "refugee", "refuse", "regard", "regarding", "regardless",
        "regime", "region", "regional", "register", "regular", "regularly", "regulate", "regulation", "reinforce", "reject",
        "relate", "relation", "relationship", "relative", "relatively", "relax", "release", "relevant", "relief", "religion",
        "religious", "rely", "remain", "remaining", "remarkable", "remember", "remind", "remote", "remove", "repeat",
        "repeatedly", "replace", "reply", "report", "reporter", "represent", "representation", "representative", "Republican", "reputation",
        "request", "require", "requirement", "research", "researcher", "resemble", "reservation", "resident", "resist", "resistance",
        "resolution", "resolve", "resort", "resource", "respect", "respond", "respondent", "response", "responsibility", "responsible",
        "rest", "restaurant", "restore", "restriction", "result", "retain", "retire", "retirement", "return", "reveal",
        "revenue", "review", "revolution", "rhythm", "rice", "rich", "ride", "rifle", "right", "ring",
        "rise", "risk", "river", "road", "rock", "role", "roll", "romantic", "roof", "room",
        "root", "rope", "rose", "rough", "roughly", "round", "route", "routine", "rule", "running",
        "rural", "rush", "sacred", "safe", "safety", "sake", "salad", "salary", "sale", "sales",
        "salt", "same", "sample", "sanction", "sand", "satellite", "satisfaction", "satisfy", "sauce", "save",
        "saving", "scale", "scandal", "scared", "scenario", "scene", "schedule", "scheme", "scholar", "scholarship",
        "school", "science", "scientific", "scientist", "scope", "score", "scream", "screen", "script", "search",
        "season", "seat", "second", "secret", "secretary", "section", "sector", "secure", "security", "seek",
        "seem", "segment", "seize", "select", "selection", "self", "sell", "Senate", "senator", "send",
        "senior", "sense", "sensitive", "sentence", "separate", "sequence", "series", "serious", "seriously", "serve",
        "service", "session", "settle", "settlement", "seven", "several", "severe", "sexual", "shade", "shadow",
        "shake", "shall", "shape", "share", "sharp", "sheer", "sheet", "shelf", "shell", "shelter",
        "shift", "shine", "ship", "shirt", "shock", "shoe", "shoot", "shooting", "shop", "shopping",
        "shore", "short", "shortly", "shot", "should", "shoulder", "shout", "show", "shower", "shrug",
        "shut", "sick", "side", "sigh", "sight", "sign", "signal", "significance", "significant", "significantly",
        "silence", "silent", "silver", "similar", "similarly", "simple", "simply", "since", "sing", "singer",
        "single", "sink", "sister", "site", "situation", "size", "skill", "skin", "sky", "slave",
        "sleep", "slice", "slide", "slight", "slightly", "slip", "slow", "slowly", "small", "smart",
        "smell", "smile", "smoke", "smooth", "snap", "snow", "so", "soccer", "social", "society",
        "soft", "software", "soil", "solar", "soldier", "solid", "solution", "solve", "some", "somebody",
        "somehow", "someone", "something", "sometimes", "somewhat", "somewhere", "song", "soon", "sophisticated", "sorry",
        "sort", "soul", "sound", "soup", "source", "south", "southern", "space", "Spanish", "speak",
        "speaker", "special", "specialist", "species", "specific", "specifically", "speech", "speed", "spend", "spending",
        "spin", "spirit", "spiritual", "split", "spokesman", "sport", "spot", "spread", "spring", "square",
        "squeeze", "stability", "stable", "staff", "stage", "stair", "stake", "stand", "standard", "standing",
        "star", "stare", "start", "state", "statement", "station", "statistics", "status", "stay", "steady",
        "steal", "steel", "step", "stick", "still", "stock", "stomach", "stone", "stop", "storage",
        "store", "storm", "story", "straight", "strange", "stranger", "strategic", "strategy", "stream", "street",
        "strength", "strengthen", "stress", "stretch", "strike", "string", "strip", "stroke", "strong", "strongly",
        "structure", "struggle", "student", "studio", "study", "stuff", "stupid", "style", "subject", "submit",
        "subsequent", "substance", "substantial", "succeed", "success", "successful", "such", "sudden", "suddenly", "sue",
        "suffer", "sufficient", "sugar", "suggest", "suggestion", "suicide", "suit", "summer", "summit", "super",
        "supply", "support", "supporter", "suppose", "supposed", "Supreme", "sure", "surely", "surface", "surgery",
        "surprise", "surprised", "surprising", "surround", "survey", "survival", "survive", "survivor", "suspect", "sustain",
        "swear", "sweep", "sweet", "swim", "swing", "switch", "symbol", "symptom", "system", "table",
        "tablespoon", "tactic", "tail", "take", "tale", "talent", "talk", "tall", "tank", "tape",
        "target", "task", "taste", "tax", "taxpayer", "teach", "teacher", "teaching", "team", "tear",
        "teaspoon", "technical", "technique", "technology", "teen", "teenager", "telephone", "telescope", "television", "tell",
        "temperature", "temporary", "tend", "tendency", "tennis", "tension", "tent", "term", "terms", "terrible",
        "territory", "terror", "terrorism", "terrorist", "test", "testify", "testimony", "testing", "text", "than",
        "thank", "that", "theater", "their", "them", "theme", "themselves", "then", "theory", "therapy",
        "there", "therefore", "these", "they", "thick", "thin", "thing", "think", "thinking", "third",
        "thirty", "this", "those", "though", "thought", "thousand", "threat", "threaten", "three", "throat",
        "through", "throughout", "throw", "thus", "ticket", "tide", "tight", "time", "tiny", "tire",
        "tired", "tissue", "title", "tobacco", "today", "together", "tomato", "tomorrow", "tone", "tongue",
        "tonight", "tool", "tooth", "topic", "toss", "total", "totally", "touch", "tough", "tour",
        "tourist", "tournament", "toward", "towards", "tower", "town", "trace", "track", "trade", "tradition",
        "traditional", "traffic", "tragedy", "trail", "train", "training", "transfer", "transform", "transformation", "transition",
        "translate", "transportation", "travel", "treat", "treatment", "treaty", "tree", "tremendous", "trend", "trial",
        "tribe", "trick", "trip", "troop", "trouble", "truck", "true", "truly", "trust", "truth",
        "try", "tube", "tunnel", "turn", "twelve", "twenty", "twice", "twin", "twist", "type",
        "typical", "typically", "ugly", "ultimate", "ultimately", "unable", "uncle", "under", "undergo", "understand",
        "understanding", "unfortunately", "uniform", "union", "unique", "unit", "universal", "universe", "university", "unknown",
        "unless", "unlike", "unlikely", "until", "unusual", "upon", "upper", "urban", "urge", "used",
        "useful", "user", "usual", "usually", "utility", "vacation", "valley", "valuable", "value", "variable",
        "variation", "variety", "various", "vary", "vast", "vegetable", "vehicle", "venture", "version", "versus",
        "very", "vessel", "veteran", "victim", "victory", "video", "view", "viewer", "village", "violate",
        "violation", "violence", "violent", "virtual", "virtually", "virtue", "virus", "visible", "vision", "visit",
        "visitor", "visual", "vital", "voice", "volume", "volunteer", "vote", "voter", "vulnerable", "wage",
        "wait", "wake", "walk", "wall", "wander", "want", "warm", "warn", "warning", "wash",
        "waste", "watch", "water", "wave", "way", "weak", "wealth", "wealthy", "weapon", "wear",
        "weather", "wedding", "week", "weekend", "weekly", "weigh", "weight", "welcome", "welfare", "well",
        "west", "western", "what", "whatever", "wheat", "wheel", "when", "whenever", "where", "whereas",
        "whether", "which", "while", "whisper", "white", "whole", "whom", "whose", "why", "wide",
        "widely", "widespread", "wife", "wild", "will", "willing", "wind", "window", "wine", "wing",
        "winner", "winter", "wipe", "wire", "wisdom", "wise", "wish", "with", "withdraw", "within",
        "without", "witness", "woman", "wonder", "wonderful", "wood", "wooden", "word", "work", "worker",
        "working", "works", "workshop", "world", "worried", "worry", "worth", "would", "wound", "wrap",
        "write", "writer", "writing", "wrong", "yard", "yeah", "year", "yellow", "yesterday", "yield",
        "young", "your", "yours", "yourself", "youth", "zone"
    )
    
    fun generate(wordCount: Int): PassphraseResult {
        require(wordCount in 3..10) { "Word count must be between 3 and 10" }
        
        val random = SecureRandom()
        val words = mutableListOf<String>()
        
        repeat(wordCount) {
            val word = WORD_LIST[random.nextInt(WORD_LIST.size)]
            val capitalized = word.replaceFirstChar { it.uppercase() }
            words.add(capitalized)
        }
        
        val passphrase = words.joinToString("-")
        return PassphraseResult(passphrase, wordCount)
    }
}
